apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  sessionAffinity: ClientIP
  ports:
    - port: 80
      nodePort: 30500
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
