apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: gluster
  resources:
    requests:
      storage: 2Gi
